mkdir -p .github/workflows
cat > .github/workflows/build.yml << 'EOF'
name: ci
on:
  push:
    branches: [ "main" ] # Update this to whatever your default branch is

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, GitHub Actions!"
